name: Build Wheel Package


on:
  pull_request:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Count Commits with Prefix
      id: count-commits
      run: |
        echo "COUNT_COMMITS_FIX=$(git log --oneline --grep="fix:" | wc -l)" >> $GITHUB_ENV
        echo "COUNT_COMMITS_FEAT=$(git log --oneline --grep="feat:" | wc -l)" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: pip install setuptools wheel twine
    
    - name: Build package
      run: python setup.py bdist_wheel
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*.whl


  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Create Release
        run: |
          gh release create --draft --repo ${{ github.repository }} ${{ github.ref_name }} dist/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish-pypi:
    needs: [build]
    environment: pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
